### ISSUE TITLE
Says User Isn't Signed in Properly When Trying to Log In with Quantimodo account

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#1]
I'm logged in with 

Quantimodo
qB1ggerstaff!q

**Comment by quintstoffers** [comment]
Does the settings screen show the account? Also, what's the version number of QuantiModo? It should have a "Content coming soon" message after signing in.

**Comment by mikepsinn** [comment]
Yes and yes.

**Comment by mikepsinn** [comment]
I mean the version is 1.0.8

**Comment by mikepsinn** [comment]
For qm. And 0.9 for qs
