### ISSUE TITLE
Add Sleep as Android for Non-Root Users

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#11]
https://sites.google.com/site/sleepasandroid/doc/developer-api

**Comment by quintstoffers** [comment]
It already does Sleep as Android. This is just for non-root functionality
which would require some changes apart from simply adding a converter.

**Comment by mikepsinn** [comment]
Or Should it be in the regular qm app? Or should there be 2 versions of qm
sync?
On Jan 25, 2014 10:37 AM, "Quint Stoffers" notifications@github.com wrote:

> It already does Sleep as Android. This is just for non-root functionality
> which would require some changes apart from simply adding a converter.
> On Jan 25, 2014 5:36 PM, "Mike P. Sinn" notifications@github.com wrote:
> 
> > https://sites.google.com/site/sleepasandroid/doc/developer-api
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mikepsinn/QuantiModo-Sync/issues/11>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync/issues/11#issuecomment-33293111
> .

##

**Comment by quintstoffers** [comment]
It makes no sense to have it in the main QM app. This should be in sync,
it's syncing after all.

**Comment by mikepsinn** [comment]
okey dokey.  maybe @GaneshVarahade can do this?  @Quipeace add any more instructions that you can think of. thanks!

**Comment by GaneshVarahade** [comment]
@mikepsinn and @Quipeace As of now I am going through the code.

**Comment by mikepsinn** [comment]
@GaneshVarahade okey dokey.

**Comment by quintstoffers** [comment]
Since there's already a converter for root users I marked this as low priority.
