### ISSUE TITLE
Fix Units on myfitnesspal converter

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#12]
This needs to be modified 

https://github.com/mikepsinn/QuantiModo-Sync/blob/a8a4ef334c17ab99743919648f83d3b81fe91e28/src/com/quantimodo/etl/MyFitnessPalConverter.java

to get the correct units from the MFP android app database

here:

https://drive.google.com/folderview?id=0B5728AmQzoPQQ2xrTzJRa1RNUWM&usp=sharing

**Comment by quintstoffers** [comment]
Are the units in a separate database? If so, that's a bit of a problem
since the ETL can't handle that now.

**Comment by mikepsinn** [comment]
@Quipeace i looked at the db again and  i guess it doesn't have units so i just changed them all to servings. https://github.com/mikepsinn/QuantiModo-Sync/commit/b612012d553c4147113b5c6bdc24e9c460158b25
