### ISSUE TITLE
Add Any Information a New Developer Will Need to Get Started to the Wiki

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#16]
@Quipeace I added everything that I could think of here: https://github.com/mikepsinn/QuantiModo-Sync/wiki

Do you see anything missing?

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
where is font "sans-serif-light"?

**Comment by mikepsinn** [comment]
Comes with android
Know your documentation ;)
Quint • 4 mins
Wenying Zhu
yes, I understood
Wenying • 4 mins
very good
4 mins
Mike Sinn
Quint Stoffers
Roboto Light is available since API 14
Quint • 4 mins
Wenying Zhu
ah, I understood.
thanks.
project is in API 17.
Wenying • 3 mins
Quint Stoffers
That's the target
Look at min-api
If min is set to 17 please set it to 14, but target should be at 17, or ideally 19.
Quint • 2 mins
Wenying Zhu
min-api is api 14.
Wenying • 2 mins
Quint Stoffers
Depends on what SDKs you have
Good.
Quint • 2 m

**Comment by zhuwenying** [comment]
Hi, Mr. Mike.
what is my sync account?
I have tested with my rooted android Nexus.
I am getting account with empty, now.
Thanks.

**Comment by mikepsinn** [comment]
Hi, @zhuwenying !

Sorry, I just saw this. 

You can just make your own account. 

Does that answer your question?
