### ISSUE TITLE
Add Screenshots and Graphics for QM Sync in Play Store and Wiki

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#18]
Also in the portfolio project.  Make sure to list the supported apps in the descriptions and put portfolio shortcode in the portfolio project.

**Comment by jentrifule** [comment]
https://github.com/mikepsinn/QuantiModo-Sync-Android/wiki/Google-Play-Store
https://drive.google.com/?usp=folder&authuser=0#folders/0B-t22a_LObpzVC1sVUZrWEFXMEk
https://play.google.com/apps/publish/?dev_acc=02996410067148046724#MarketListingPlace:p=com.quantimodo.sync

**Comment by mikepsinn** [comment]
Please put the word sync and the resolutions in the file names of the images.  Also please embed all images in the wiki as well. 

Also, please update the portfolio and wiki with the list of compatible apps: https://docs.google.com/document/d/1pabrhLWx0inckyup-jiNnwDcC_55ZeTUo1FQ1CKjCiU/edit?usp=sharing

Thanks!

**Comment by jentrifule** [comment]
Re: Please put the word sync and the resolutions in the file names of the images. Also please embed all images in the wiki as well.
I've put the Resolutions in the name of each image.
Please see: https://github.com/mikepsinn/QuantiModo-Sync-Android/wiki/Google-Play-Store
Do you want me to resize the wiki's images?

**Comment by mikepsinn** [comment]
That's ok. thanks!
