### ISSUE TITLE
Putting measurementsSync for Accupedo app is failed.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#20]
String response = Ion.with(context, QUANTIMODO_ADDRESS +"api/measurements/v2")
                 .setTimeout(10000 + (20 \* measurements.size()))
                     .setHeader("Authorization", "Bearer " + token)
                 .setJsonObjectBody(variables)
                 .asString()
                 .get();

QUANTIMODO_ADDRESS = "https://quantimo.do/"

test result : 
response : {"status":"404",
                   "success": false,
                   "error":"Unknown unit",
                   "row":"0",
                   "variable":"unit"}

Now, for Accupedo app, the value of variable "unit" of QMJsonVariable is "steps".

**Comment by quintstoffers** [comment]
I added the unit, should be OK now.
