### ISSUE TITLE
It can't be tried to sync in next sync  for variables that were failed.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#21]
this is the test data.

first sync : failed
      "steps", (54, 1391534969459)
      "Walk/Run Distance", (0.023487810045480728, 1391534969459)
      "Calories Burned", (1.6363236904144287, 1391534969459)

second sync : 
      "steps", (518, 1391536513810)
      "Walk/Run Distance", (0.2253100834786892, 1391536513810)
      "Calories Burned", (15.696556329727173, 1391536513810)

In the second sync, first failed sync variables are not saved.
So, for failed sync variables, it can't be tried to sync in next sync.

my think : 
      ArrayList<QmJsonVariable> variables = new ArrayList<QmJsonVariable>();

```
  This variable is the local variable of functions putMeasurementsSynchronous().
  I think this variable need to be the member variable of class QuantimodoClient.
  If the memory usage is not effective,  we can apply with limit sync count.
  Anyway, it is not perfect to put sync measurements to database only once.
```

**Comment by mikepsinn** [comment]
@zhuwenying what does this mean?

Can you fix it?

**Comment by zhuwenying** [comment]
Now, this issue was fixed by Mr. Quint.

**Comment by mikepsinn** [comment]
OK. Find the commit that fixed it, paste the link in the comments, and close the issue.  Thanks.

**Comment by zhuwenying** [comment]
it was fixed in 
https://github.com/mikepsinn/QuantiModo-Sync/commit/9ed56f14d18b504d163c63049fec28b0549165ef
