### ISSUE TITLE
The first required field of Accupedo converter is not checking with database.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#22]
for (int requiredFieldNumber = 1; requiredFieldNumber <
      REQUIRED_FIELD_NAMES.length; requiredFieldNumber++)  
{  
    if (!table.hasField(REQUIRED_FIELD_NAMES[requiredFieldNumber]))  
        return null;  
}

Why REQUIRED_FIELD_NAMES[0] was excepted?
After this check, REQUIRED_FIELD_NAMES[0] is using.

Now, error is not occured, becauase "diaries" table has the first filed "steps".
But I think it need to be fixed.

**Comment by mikepsinn** [comment]
@zhuwenying 

can you fix this?

**Comment by zhuwenying** [comment]
yes, I can fix it.

**Comment by zhuwenying** [comment]
This issue was fixed on 
https://github.com/mikepsinn/QuantiModo-Sync/commit/73aaf6f611be5a452b9ae7afb4f1ab111bf2fef4
