### ISSUE TITLE
HowAreYouFeeling - List possible rating types, match to existing variables in database

### ISSUE THREAD

**Issue by quintstoffers** [Abolitionist-Project/QuantiModo-Sync-Android#24]
[HowAreYouFeelingConverter.java](/mikepsinn/QuantiModo-Sync/blob/master/src/com/quantimodo/etl/HowAreYouFeelingConverter.java)

This converter currently uses the rating types defined in the database as variable name. These rating types should be documented, and where possible it should use variables that are already in the existing QuantiModo database.

**Comment by mikepsinn** [comment]
@zhuwenying can you do this?

**Comment by zhuwenying** [comment]
I need to access to quantimodo.do/phpAdmin.
I think the table datas are not same in both of dev.quantimodo.do and quantimdo.do.

**Comment by mikepsinn** [comment]
Do you mean the database structures are different? What makes you think that? They should be identical.

**Comment by zhuwenying** [comment]
no, it is not.
I tried to use the variable, category, unit table datas with dev.quantimo.do.
But, these records are not same with quantimo.do.
I have checked this with https://quantimo.do/analyze.

Sturcture is same, but records are not same.
So, I need to access to quantimo.do/phpAdmin.

**Comment by mikepsinn** [comment]
ok you should have access now
