### ISSUE TITLE
T2MoodTracker - Track all aspects of mood

### ISSUE THREAD

**Issue by quintstoffers** [Abolitionist-Project/QuantiModo-Sync-Android#25]
[T2MoodTrackerConverter.java](/mikepsinn/QuantiModo-Sync/blob/master/src/com/quantimodo/etl/T2MoodTracker.java)

This converter currently stores everything as "Overall Mood". Track all other aspects as well, use existing variable names where possible.

**Comment by mikepsinn** [comment]
@zhuwenying can you do this?

**Comment by zhuwenying** [comment]
yes, I can do

**Comment by mikepsinn** [comment]
OK.  Thanks.  Make sure to close the version 1.1 issues first.
On Feb 8, 2014 1:50 PM, "zhuwenying" notifications@github.com wrote:

> yes, I can do
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync/issues/25#issuecomment-34553916
> .

##
