### ISSUE TITLE
Sync result for Accupedo converter is failed with error "Timestamp too far in future".

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#26]
1. new Accupedo data time 
   year = 2014, month = 2, day = 6, hour = 8, minute = 11 steppingDuration = 33107
2. get time with GregorianCalendar in accupedo converter
   final long inputTime = (new GregorianCalendar(year, month - 1, day, hour, minute, 0)).getTimeInMillis();
   final long outputTime = (inputTime - steppingDuration);

inputTime = 1391645460000
outputTime = 1391645426893
1. sync response : 
   {"status":"400","success": false,"error":"Timestamp too far in future","row":"0","variable":"timestamp"}

in here, timestamp = outputTime = 1391645426893
1. test result
   Time is initializing with GregorianCalendar in the default timezone and the default  
   locale.
   I think current timezone and current locale need.

**Comment by quintstoffers** [comment]
Thanks, looks like the timestamp is in milliseconds. It should be divided
by 1000 so it's in seconds.

**Comment by zhuwenying** [comment]
this issue had resolved.
final long outputTime = (inputTime - steppingDuration) / 1000;

sync response: 
{"status":"200","success": true}

Accupedo converter is good.

**Comment by mikepsinn** [comment]
@zhuwenying did you see the data in the database?

**Comment by zhuwenying** [comment]
I am checking in database.
