### ISSUE TITLE
All sync data don't save to measurement table on database.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#27]
- Accupedo app sync response : { "status" : "200", "success" : true}
- Cadiograph app sync response : { "status" : "200", "success" : true}
- Good Day Journal app sync response : { "status" : "200", "success" : true }

total synced measurements : 17 

https://dev.quantimo.do/phpmyadmin/

synced  measurements didn't saved to measurements table in quantimodo db.

**Comment by quintstoffers** [comment]
It syncs to quantimo.do, not the dev site.

**Comment by zhuwenying** [comment]
how can I login to quantimo.do/phpmyadmin?
I have no account.

**Comment by mikepsinn** [comment]
@Quipeace can we set it up to send to the dev server for testing? or should i make wenying an account on production?

@zhuwenying did you make a user account at quantimo.do?  If so, you should be able to go to https://quantimo.do/analyze/ and see if your data got sent.

**Comment by quintstoffers** [comment]
Yes, change the string in QuantimodoClient.java to dev.quantimo.do.

**Comment by mikepsinn** [comment]
@zhuwenying got that?

you have an account on dev.quantimo.do/phpmyadmin
wenying
wenying123

**Comment by zhuwenying** [comment]
yes, I understood.
I will change url in QuantimodoClient.java with dev.quantimo.do.

**Comment by quintstoffers** [comment]
Don't commit that change, please.

**Comment by zhuwenying** [comment]
yes, I understand.
I will test only.
