### ISSUE TITLE
sync measurement is failed for "How Are You Feeling" converter.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#28]
1. "How Are You Feeling" app database test data
   
    id             time                 feeling      levelid      note
    1    1391698982772            0              5
    2    1391702252389            0              7
2. Quantimodo MeasurementSet
   
    name   category   unit   combinationOperation     source            measurements
   feeling    Mood    feeling           EAN       How Are You Feeling   (1391698982, 1.0, -1)
                                                                                                      (1391702252, 3.0, -1)
3. Sync Response
   
   token : 1c592cd454a7d61219f50c608d352903ce65eed3
   response : {"status":"404","success": false,"error":"Unknown  
                      unit","row":"0","variable":"unit"}

**Comment by mikepsinn** [comment]
@zhuwenying can you fix this?

**Comment by zhuwenying** [comment]
To fix this, I need to access to quantimodo.do/phpAdmin.
Because, when making "quantimodo measurement set", "name", "category", "unit", "source", "combin" informations should be needed.
These infos are in quantimodo.do/phpAdmin.

**Comment by mikepsinn** [comment]
you should have access now

**Comment by zhuwenying** [comment]
this issue was fixed on 
https://github.com/mikepsinn/QuantiModo-Sync/commit/5205a017c8fd9623c1b6fc8dbd28063e65e2b8ad
1. add new unit "0 to 10" in database.
2. update unit "(-4 to 4)" with "-4 to 4" in database
3. fixed converter unit, source issue on quantimodo-sync project.

Best Regards

**Comment by mikepsinn** [comment]
thanks, @zhuwenying !
