### ISSUE TITLE
Accupedo sync datas don't display correctly on https://quantimo.do/analyze/

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#29]
1. converter data
   - stepsMeasurement
     value = 354.0
     Duration = 155070
     timestamp = 1391803704
   - distanceMeasurement
     value = 0.1539755612611706
     Duration = 155070
     timestamp = 1391803704
   -  caloriesMeasurement
     value = 10.77215576171875
     Duration = 155070
     timestamp = 1391803704
2. sync data
   
   Steps = 354.0
   Walk/Run Distance = 0.15397556126117706
   Walk/Run Distance = 10.77215576171875
3. display data
   
   steps (Accupedo) = 354.0
   Walk/Run Distance (Accupedo) = 10.77
4. test Result
   
   10.77 is "Calories Burned", not "Walk/Run Distance".
   "Walk/Run Distance" should be "0.154".
   
   I think the reason is in making measurementSet in AccupedoConverter.

if(distanceMeasurements.size() != 0)
     measurementSets.add(new MeasurementSet("Walk/Run Distance", "Goals", "count", MeasurementSet.COMBINE_SUM, "Accupedo", distanceMeasurements));

if(caloriesMeasurements.size() != 0)
    measurementSets.add(new MeasurementSet("Walk/Run Distance", "Goals", "count", MeasurementSet.COMBINE_SUM, "Accupedo", caloriesMeasurements));

For both of distanceMeasurements and caloriesMeasurements, 
category, name and unit are same.

**Comment by mikepsinn** [comment]
@zhuwenying can you fix it?

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
I can fix, but I think it should be approved by Mr. Quint.

**Comment by mikepsinn** [comment]
ok. fix it.  we can revert if it's a problem.  thanks!

**Comment by mikepsinn** [comment]
@zhuwenying did you fix this?  

Also, make any issues that you create related to this Version 1.1 milestone task a milestone of Version 1.1 as well. 

Thanks!

**Comment by zhuwenying** [comment]
Sync, save, display for Accupedo app are all correct.
This issue was fixed on https://github.com/mikepsinn/QuantiModo-Sync/commit/76e1e33adf1a4e3dfe05c85d59fe9395448c3f2f.
