### ISSUE TITLE
sync data and display data are not same for SleepAsAndroid app.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#32]
1. sync data
   
   Sleep Duration (SUM): (1391508571, 52.0, 3151)
                                       (1391825593, 11.0, 711)
                                       (1391852443, 442.0, 26554)
   
   Sleep Cycles(SUM) : (1391508571, 0.0, -1)
                                    (1391825593, -1.0, -1)
                                    (1391852443, 7.0, -1)
   
   Sleep Rating(MEAN) : (1391508571, 0.0, -1)
                                      (1391825593, 0.0, -1)
                                      (1391852443, 0.0, -1)
   
   Sleep Quality(MEAN) : (1391508571, 0.0, -1)
                                       (1391852443, 0.5909090638160706, -1)
2. display data on https://quantimo.do/analyze/
   
   Sleep Duration(min) from Sleep As Android : 226.50
   Sleep Cycles(event) from Sleep As Android : 3.0
   Sleep Rating(/6) from Sleep As Android : 0.00
   Sleep Quality(/1) from Sleep As Android : 0.59

for Duration and Cycle, it is correct?
I can't check it is ok or not.
I think it need to check on web service.

Also, I have synced for three timestamps as above.
But, displaying is in one timestamp, only.

**Comment by mikepsinn** [comment]
@zhuwenying please change duration and cycles to "MEAN" instead of "SUM".  If someone forgets to track their sleep, SUM will lead to erroneous grouping. 

Also, i thought @Quipeace  told you how to point your version at dev.quantimo.do rather that quantimo.do, didn't he?

So shouldn't you be checking dev.quantimo.do/phpmyadmin?

**Comment by zhuwenying** [comment]
Yes, I understood.
when sync to dev.quantimo.do, error occured.
parsing is failing always with dev.quantimo.do.

**Comment by mikepsinn** [comment]
@zhuwenying i made you an account on quantimo.do.  please see why it's working there but not on dev.quantimo.do.  we need to fix whatever the problem is because we will be using dev for the production server soon.

**Comment by zhuwenying** [comment]
1. sync and save data are all correct.
2. for display, when I select date range with "hour" or "minute", display is correct.
3. when I select date range with "day" or "week", SUM and MEAN is same with MEAN.
   it is correct?
   For SUM and MEAN, display result is same.

**Comment by mikepsinn** [comment]
Is it a single measurement during that week? The sum and the mean of a single value will always be the same.

**Comment by zhuwenying** [comment]
As above, Sync datas consist of three timestamp in one day.
So, when selecting hours or mimutes, 3 timestamp display each other.
But, when selecting days or weeks, 3 timestamp disply with one timestamp and it is mean of 3 timestamps.

**Comment by mikepsinn** [comment]
@zhuwenying I'm not sure what you mean, but it's probably fine. 

Also, please install this: https://chrome.google.com/webstore/detail/evernote-web-clipper/

and use it to take screenshots to illustrate what you're talking about like i do. 

thanks!

**Comment by zhuwenying** [comment]
I have created screnshots and shared with 
https://www.evernote.com/shard/s373/sh/89397ac3-c1a5-4774-9333-f12b4a4d13d3/0e9dffe9a02ecc34b5e4a8239dd8a823

Best Regards.

**Comment by mikepsinn** [comment]
ok.  thanks. i think it's fine.  don't worry about it for now.
