### ISSUE TITLE
Sync for MyFitnessPal is failed.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#33]
1. sync data
   
   name = "chicken soup"
   category = "Foods"
   unit = "serving"
   combin = SUM
   source = "MyFitnessPal"
   measurement = (1394236800, 1.0, -1)
2. sync response
   
   token : 5d8b9e3701fe876988f7d2958380e3e0d2bdd32d
   response : 
                   {"status":"404","success": false,"error":"Unknown 
                     unit","row":"0","variable":"unit"}
3. result
   
   unit "serving" is the unknown unit.

**Comment by mikepsinn** [comment]
@zhuwenying add the unit serving to the units table in the database

**Comment by zhuwenying** [comment]
yes, I unerstood.

**Comment by zhuwenying** [comment]
1. added unit "serving" to database.
2. sync successed.
3. sync data saved on database as below.
   
   name : chicken soup
   category : Foods
   unit : serving
   combin : SUM
   source : MyFitnessPal
   measurement : (1391815800, 1.0, -1)
4. value "1.0" doesn't display on https://quantimo.do/analyze/.
   Only, category and name display.

**Comment by mikepsinn** [comment]
@zhuwenying did you try sending multiple measurements?

**Comment by mikepsinn** [comment]
@zhuwenying set the milestone on these kinds of issues to version 1.1 because they're related to another issue for milestone 1.1

**Comment by zhuwenying** [comment]
values are displayed on dashboard, correctly.
So, sync for MyFitnessPal is good.
