### ISSUE TITLE
sync, save, display for Good Day Journal App are all correct.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#35]

**Comment by mikepsinn** [comment]
@zhuwenying please upload any spreadsheet documentation you make to google drive.

then make the google spreadsheet editable by anyone with the link.

then paste the sharing link in a wiki entry.  

For instance, you would put a link to your google spreadsheet for the MyFitnessPal converter test here:  https://github.com/mikepsinn/QuantiModo-Sync/wiki/Android-App:-MyFitnessPal

**Comment by zhuwenying** [comment]
I have uploaded and shared test documents.
https://drive.google.com/#folders/0B9VlU7GDYGaUT19XYmdaWFRBZDg

**Comment by mikepsinn** [comment]
thanks!

You probably don't need to do that much work on this.  However, if you ever do make spreadsheets in the future, please use google spreadsheets from now on, so that they're easily editable.

**Comment by zhuwenying** [comment]
Yes, I understood.

thanks.

**Comment by mikepsinn** [comment]
thanks you!
