### ISSUE TITLE
sync for T2 Mood Tracker App is empty.

### ISSUE THREAD

**Issue by zhuwenying** [Abolitionist-Project/QuantiModo-Sync-Android#36]
For T2 Mood Tracker App, sync measurement list is empty.
So, sync is successed, but anything don't save on database.
And, anything don't display on https://quantimo.do/analyze/.

This issue is relatived with issue 25.

Note:
T2 Mood Tracker App has 6 groups and 10 scales for each group.
So, 60 variables are needed.
There are no variables to match with these variables on database, now.

I think as followed.
1. adding 6 variables "Depression", "Anxiety", "General Well-Being", "Head Injury", "PTS(Post-traumatic Stress), "Stress" on database.
These variables are corresponded with groups on T2 Mood Tracker App.
2. The measurement value of each variable should be calculated with mean of values of 10 detailed scales.

One group of T2 Mood Tracker App has 10 scales.
If we display individually, we need total 60 variables for T2 Mood Tracker.
It is not useful.
So, we  can define one group as one variable and calculate the value of one variable with mean of the values of 10 scales.
The unit of all variables will be "%".

How about, Mr. Mike?
Best Regards.

**Comment by mikepsinn** [comment]
@zhuwenying we need all the variables.

but i think we might be importing the curetogether database. so let me think about it.

**Comment by mikepsinn** [comment]
@zhuwenying can you have it create the variables that don't exist we need the same way the myfitnesspal does it?

@Quipeace what's the easiest way to handle this?

**Comment by zhuwenying** [comment]
yes, I can make same as myfitnesspal.
But, I am not sure for scale names for each group.
Each scale have min lavel and max lavel, but not name.
How to set the scale name?
In other words, how to match one scale to one variable?
If we can get this, it is sure to sync same as myfitnesspal.

Best Regards.

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
How about the rule to make variable name as follow?

parameter : groupname, scale_min_label, scale_max_label
variable name : groupname(scale_min_label / scale_max_label)
unit : %
category : Mood
source : T2 Mood Tracker

example : path : Add Variable -> Mood - > Anxiety(Worried/Untroubled) -> T2 Mood Tracker
                Hint : Anxiety(Worried/Untroubled) (%) from T2 Mood Tracker : 50

Best Regards.

**Comment by mikepsinn** [comment]
https://play.google.com/store/apps/details?id=com.t2.vas&hl=en

@zhuwenying just use all the scale_max_labels as the variable names

what's the range of the values in the database?

i thought it went from -10 to 10 ?

**Comment by zhuwenying** [comment]
Range of the values will be "0 ~ 100".
This means percent between min label and max label.
So, for example "value = 50" means half of min label and max label.

Best Regards.

**Comment by mikepsinn** [comment]
doesn't t2 use -4 to 4 unit?

**Comment by zhuwenying** [comment]
yes, sir.
-4 to 4 unit is using on HowAreYouFeeling app.

Best Regards.

**Comment by mikepsinn** [comment]
but T2 uses % in their app?

the unit should be the same that the app uses.  

we do unit conversions later if necessary.  no unit conversion should be done in the android ETL modules

**Comment by mikepsinn** [comment]
ok, so yes use the max_scale_label as variable name and & as unit.

**Comment by zhuwenying** [comment]
T2 Mood Tracker doesn't have unit.
Only, this app use min label, max label and value.
So, when makeing sync measurement, converter is using % unit.
If we don't use unit %, we can use unit with empty string.

Best Regards.

**Comment by mikepsinn** [comment]
i looked at their database.

the values range from 0 to 100.  that means the unit we should use is percent.

**Comment by zhuwenying** [comment]
Yes, it is right.
So, I will use scale_max_label as variable name.
But, I can't understand & unit.
I can't use % unit?

Best Regards.

**Comment by quintstoffers** [comment]
This sounds so much more complex that it should be? T2 tracks specific
aspects of mood which should be inserted just like that.

**Comment by mikepsinn** [comment]
The T2 variable naming thing is weird. 

but using the max label is fine for the variable name

**Comment by mikepsinn** [comment]
https://github.com/mikepsinn/QuantiModo-Sync/blob/9ed56f14d18b504d163c63049fec28b0549165ef/src/com/quantimodo/etl/T2MoodTrackerConverter.java

**Comment by quintstoffers** [comment]
Can't we match some variables to ones we're tracking in MoodiModo or other
trackers? It'd be a bit messy if we have a variable "Hostile" and
"Hostility" for instance.

**Comment by mikepsinn** [comment]
Synonyms and variations are going to be unavoidable.  

We've got foods and medications. 

we going to need some kind of way to deal with this kind of thing automatically, eventually. and we're going to need all the possible variations to be in the variables table to do that.  SO that we can link them. 

don't you think?

**Comment by quintstoffers** [comment]
They're unavoidable on a global scale, but not on a personal one.
Furthermore we control this convertor, so why not make sure it works well?

What if someone switches from T2 to MoodiModo? He'd have a ton of
duplicates. If another app has QuantiModo support built in the user
wouldn't be as tempted to switch to another, so he'd not have this issue.

**Comment by zhuwenying** [comment]
So, how to I convert?
Some of variables can be matched to ones on other trackers and MoodiModo.
But, it is impossible for all variables.

**Comment by mikepsinn** [comment]
if it's not obvious, just use the max label from T2

**Comment by zhuwenying** [comment]
yes, I understood.

Best Regards.

**Comment by mikepsinn** [comment]
thanks!
