### ISSUE TITLE
Fix MyFitnessPal ETL Converter to send measurements with Correct Units

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#40]
Install MFP on rooted device. 

Log in with mikesinn 
and the secret password.

Find the units in the MFP android database

Modify converter to use the same ones used in the database. 

Make sure measurements are properly graphed on production after uploading. 

The source should be MyFitnessPal-Android

**Comment by quintstoffers** [comment]
Why don't we just use count? I'm not sure what it's using now, not on my pc.

**Comment by mikepsinn** [comment]
OK.  There's eventually going to be a conversion from count to serving.

**Comment by quintstoffers** [comment]
Count and serving are the same except for the name. There is no conversion.

**Comment by mikepsinn** [comment]
No.  I mean in the future with variable specific conversion. boxes of Nerds
say 25 count/serving.
On Feb 26, 2014 6:01 PM, "Quint Stoffers" notifications@github.com wrote:

> Count and serving are the same except for the name. There is no conversion.
> On Feb 27, 2014 12:44 AM, "Mike P. Sinn" notifications@github.com wrote:
> 
> > OK. There's eventually going to be a conversion from count to serving.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mikepsinn/QuantiModo-Sync-Android/issues/40#issuecomment-36193039
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync-Android/issues/40#issuecomment-36194243
> .

##

**Comment by quintstoffers** [comment]
I don't see why you'd need a conversion from count to serving. You count
servings, servings are counted.

**Comment by mikepsinn** [comment]
Excellent point. 

It's my understanding, the parlance is that an individual unit of a food is called a count. A group of units (counts) are equivalent to a serving.  I believe the serving size is established by the USDA.  

It doesn't really matter.  It would just be good to use whatever units and conversions the other food tracking apps use.

**Comment by quintstoffers** [comment]
Ah right, so a serving is a measure of weight in this case. I think we can
have a unit in both categories.
