### ISSUE TITLE
Put "Check for Update Option" in Settings

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#42]
This would link to the entry in the play store.

**Comment by quintstoffers** [comment]
What does this mean?

**Comment by mikepsinn** [comment]
I'm never sure if i'm using the most updated version of the app, so i guess this would link to the entry in the play store.

**Comment by quintstoffers** [comment]
Once it's on the play store this won't be an issue, it would be a waste to
add this.

**Comment by mikepsinn** [comment]
ok
