### ISSUE TITLE
Won't Sync when MyFitnessCompanion is checked

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#48]
I guess this is low priority. However, in this gist: https://gist.github.com/mikepsinn/11098224
first I tried to sync with MyFitnessCompanion checked.  It wouldn't do anything. The history screen remained empty.  Then I unchecked MyFitnessCompanion and it seemed to work. There were records for Medhelper, Sleep as Android, and Good Day Journal in the history screen.

**Comment by QuintiModo** [comment]
It says "no file cached", so it seems the XML just points to the wrong file?

**Comment by mikepsinn** [comment]
Thanks!  I'll check it out.

Yours truly,
Mike P. Sinn

On Sat, Apr 19, 2014 at 5:58 PM, QuintiModo notifications@github.comwrote:

> It says "no file cached", so it seems the XML just points to the wrong
> file?
> On Apr 20, 2014 12:42 AM, "Mike P. Sinn" notifications@github.com wrote:
> 
> > I guess this is low priority. However, in this gist:
> > https://gist.github.com/mikepsinn/11098224
> > first I tried to sync with MyFitnessCompanion checked. It wouldn't do
> > anything. The history screen remained empty. Then I unchecked
> > MyFitnessCompanion and it seemed to work. There were records for
> > Medhelper,
> > Sleep as Android, and Good Day Journal in the history screen.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/mikepsinn/QuantiModo-Sync-Android/issues/48>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync-Android/issues/48#issuecomment-40882940
> .

##
