### ISSUE TITLE
Can't Add Account

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#5]
@Quipeace i'll try and figure this out, i was wondering if you knew what the problem was off the top of your head?

Maybe this should go in the API or wordpress repo, but i thought i'd put it here, because i'm only experiencing it with this app?

SLIM ERROR
Missing Argument 2 for cookiesetter_set_cookie when try to connect account
mu-plugins/logged-in-cookiesetter
line 32

**Comment by quintstoffers** [comment]
Someone uploaded logged_in_cookiesetter.php again... Remove it from mu-plugins and it'll work again.

**Comment by mikepsinn** [comment]
Thanks!

On Sat, Jan 11, 2014 at 2:27 PM, Quint Stoffers notifications@github.comwrote:

> Someone uploaded logged_in_cookiesetter.php again... Remove it from
> mu-plugins and it'll work again.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync/issues/5#issuecomment-32106029
> .

##
