### ISSUE TITLE
Failed to find provider info for com.quantimodo.app.content-appdata

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#6]
Do you have any ideas about this?  

https://gist.github.com/mikepsinn/8377746

**Comment by quintstoffers** [comment]
When exactly did you get this error?

**Comment by mikepsinn** [comment]
when i tried to sync medhelper

On Sat, Jan 11, 2014 at 5:47 PM, Quint Stoffers notifications@github.comwrote:

> When exactly did you get this error?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mikepsinn/QuantiModo-Sync/issues/6#issuecomment-32110855
> .

##
