### ISSUE TITLE
Myfitnesspal doesn't sync even though it's checked

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#7]
Do you have any ideas?

https://gist.github.com/mikepsinn/8407562

**Comment by quintstoffers** [comment]
The module isn't added to ETL.java

**Comment by mikepsinn** [comment]
ah. thanks!

**Comment by mikepsinn** [comment]
Are you talking about this file?

https://github.com/mikepsinn/QuantiModo-Sync/blob/master/src/com/quantimodo/etl/ETL.java

It seems like MFP is in there?
