### ISSUE TITLE
Test All of the Apps on Your Phone and Account to Make Sure they Work

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#8]
Root phone

Install titanium backup 

Install these apps
https://github.com/mikepsinn/QuantiModo-Sync
https://github.com/mikepsinn/MoodiModo-Android
https://github.com/mikepsinn/QuantiModo-Android

Create an account using your gmail address

Install the life tracking apps in quantimodo sync already.

There's some test data in the folders here:
https://drive.google.com/a/thinkbynumbers.org/#folders/0B5bXsrxQCOy8WTcyVXFvcVlkdU0

You can restore a lot of it with titaniumbackup. 

But you can just make your own dummy data for testing, if that's easier.

If you need test data for an app that isn't in that folder, just ask me in the comments, and i can add it. 

We want to be sure we can get all the right data in the database here:
https://quantimo.do/phpmyadmin/

and that it's graphed properly here:
https://quantimo.do/dashboard/analyze/

Verify that we're getting all relevant data from the databases and that the variables are named and categorized properly. 

You can look at the databases with titaniumbackup using special features-> storage -> explore or by using the app sqlite editor.

**Comment by mikepsinn** [comment]
Then make issues for any problems you see.

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
I progressed for below steps on my rooted Google Nexus7 device.
1. installed titanium backup*root
2. installed QuantiModo-Sync
3. installed QuantiModo-Android
4. installed MoodiModo-Android
5. create account with my mail.
   WenyingZhu, recover8948@gmail.com
6. installed 10 traking apps among 14 compatible apps in Quantimodo-Sync.
   installed apps : Accupedo, Cardiograph, Good Day Journal, How are you Feeling, MedHelper,
                            MediSafe, myFitnessCompanion, MyFitnessPal, Sleep as Android, 
                            T2 Mood Tracker
   Compatible apps : Call Recorder, Data Habit, MedHelper Pro, Zombies, Run!
7. Setting/Quantimodo/Wenying Zhu/MoodiModo moods : sync checked
   Setting/Quantimodo/Wenying Zhu/Tracking apps : sync checked
8. actived sync for 10 installed apps in Quantimodo-Sync.

For above steps, I did have all correctly?

**Comment by mikepsinn** [comment]
@zhuwenying i believe so!  

Can you get it to send measurements to the database?

**Comment by zhuwenying** [comment]
yes, sir.
I have finished testing for Accupedo converter.
I will make and sent test document.

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
I have created Accupedo app testing document.
How can I share this document?
Can you give me the upload permission on google drive?

**Comment by mikepsinn** [comment]
@zhuwenying 

what is a testing document?

can you put a link here?

**Comment by mikepsinn** [comment]
Did you check and make sure all the apps could send data to the measurements table here?
https://dev.quantimo.do/phpmyadmin/
wenying
wenying123

**Comment by zhuwenying** [comment]
Now, sending sync data is failed for all measurements.
I described this in document.
I found 3 issues in this test.
I have tested for one app "Accupedo", now.

thanks.

**Comment by mikepsinn** [comment]
@zhuwenying how is this coming?

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
I am testing with new version updated by Mr. Quint.

**Comment by mikepsinn** [comment]
Thanks!

**Comment by mikepsinn** [comment]
@zhuwenying have you tested all of the apps yet?

**Comment by zhuwenying** [comment]
I can finish test until tomorrow.

**Comment by mikepsinn** [comment]
@zhuwenying please make a wiki entry for each app you tested and link to your google spreadsheet for that app in the entry.
