### ISSUE TITLE
Create a history screen

### ISSUE THREAD

**Issue by mikepsinn** [Abolitionist-Project/QuantiModo-Sync-Android#9]
use intents to communicate with the sync service

Create a history screen

So it'd have to store the sync results in a SQLite database

You can take the code for the history screen off moodimodo
https://github.com/mikepsinn/MoodiModo-Android/search?q=history&ref=cmdform

**Comment by mikepsinn** [comment]
@zhuwenying did you already do this?

**Comment by mikepsinn** [comment]
I see a history screen, but the app just crashes when i go to it.

**Comment by zhuwenying** [comment]
Hi, Mr. Mike
I have finished history screen, and Mr. Quant corrected after this.
I didn't crash, anytime.
I will check again.
Best Regards.

**Comment by quintstoffers** [comment]
It still doesn't crash here. Without a stacktrace there's little I can do.

**Comment by mikepsinn** [comment]
I just uninstalled everything and reinstalled. It still crashed when going to history. But out let me send an error report with stack trace. Do you get those quint? Our do they just go to Google?

**Comment by mikepsinn** [comment]
Here's the error:
https://gist.github.com/mikepsinn/9254686

**Comment by mikepsinn** [comment]
Any ideas?

**Comment by quintstoffers** [comment]
Uninstall what you have, install the version from git I just committed.

**Comment by zhuwenying** [comment]
I think table name is incorrect.

**Comment by mikepsinn** [comment]
OK. Thanks!

when i tried to upload the new version to play it said "Your APK needs to have the package name com.quantimodo.sync."

do you know why that is?

**Comment by mikepsinn** [comment]
i'm an idiot.  i uploaded qm-android

**Comment by quintstoffers** [comment]
Apparently the package name isn't com.quantimodo.sync, sounds like you're
uploading an old version... It wouldn't be able to upload to play anyway,
since the version number hasn't changed. I'll recompile with 1.1.0.

**Comment by mikepsinn** [comment]
uninstalled and reinstalled from play store and still got this

https://gist.github.com/mikepsinn/9255120
